name: "Tests & Static Analysis"

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  laravel-tests:

    runs-on: ubuntu-latest

    steps:
    - uses: shivammathur/setup-php@15c43e89cdef867065b0213be354c2841860869e
      with:
        php-version: '8.0'
    - uses: actions/checkout@v2
    - name: Create Database
      run: |
        mkdir -p database
        touch database/database.sqlite
    - name: Copy .env
      run: php -r "file_exists('.env') || copy('.env.example', '.env');"
    - name: Install Dependencies
      run: composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist --no-suggest --optimize-autoloader
    - name: code sniffer
      run: ./vendor/bin/phpcs --report=source ./app || true
    - name: Generate key
      run: php artisan key:generate
    - name: Directory Permissions
      run: chmod -R 777 storage bootstrap/cache
    - name: Install NPM dependencies
      run: npm install
    - name: Compile assets
      run: npm run production
    - name: Psalm
      run: vendor/bin/psalm --output-format=github
    - name: Execute tests (Unit and Feature tests) via PHPUnit
      env:
        DB_CONNECTION: sqlite
        DB_DATABASE: database/database.sqlite
      run: vendor/bin/phpunit
    - name: Upgrade Chrome Driver
      run: php artisan dusk:chrome-driver
    - name: Start Chrome Driver
      run: ./vendor/laravel/dusk/bin/chromedriver-linux > /dev/null 2>&1 &
    - name: Run Laravel Server
      run: php artisan serve > /dev/null 2>&1 &
    - name: Run Dusk Tests
      env:
        APP_ENV: local
        APP_URL: "http://127.0.0.1:8000"
        DB_CONNECTION: sqlite
        DB_DATABASE: database/database.sqlite
      run: |
        chmod -R 0755 vendor/laravel/dusk/bin/
        php artisan dusk --process-isolation

